# Generated by Django 4.1 on 2023-12-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_fabrication',
            field=models.DateField(max_length=50, verbose_name='Data Fabricacao'),
        ),
    ]
