# Generated by Django 4.1 on 2023-12-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_fabrication',
            field=models.CharField(max_length=50, verbose_name='Data Fabricacao'),
        ),
    ]
